version: 2

setup: &setup
  working_directory: ~/coacher
  docker:
    - image: circleci/node:8-browsers
jobs:
  checkout-and-install:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - coacher-{{ .Branch }}-{{ checksum "package.json" }}
            - coacher-{{ .Branch }}
            - coacher-
      - run: yarn install
      - save_cache:
          key: coacher-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  build:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: coacher-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Production Build
          command: yarn build
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout-and-install
      - test:
          requires:
            - checkout-and-install
      - build:
          requires:
            - test
