version: 2

setup: &setup
  working_directory: ~/coacher
  docker:
    - image: circleci/node:8-browsers
jobs:
  checkout-and-install:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - coacher-{{ .Branch }}-{{ checksum "package.json" }}
            - coacher-functions-{{ checksum "functions/package.json" }}
      - run: yarn install
      - save_cache:
          key: coacher-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: yarn install --cwd functions
      - save_cache:
          key: coacher-functions-{{ checksum "functions/package.json" }}
          paths:
            - "node_modules"
  test:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - coacher-{{ .Branch }}-{{ checksum "package.json" }}
            - coacher-functions-{{ checksum "functions/package.json" }}
      - run:
          name: Run tests
          command: yarn ci
  build:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - coacher-{{ .Branch }}-{{ checksum "package.json" }}
            - coacher-functions-{{ checksum "functions/package.json" }}
      - run:
          name: Production Build
          command: yarn build
  deploy-dev:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - coacher-{{ .Branch }}-{{ checksum "package.json" }}
            - coacher-functions-{{ checksum "functions/package.json" }}
      - run:
          name: Deploy
          command: yarn deploy:staging
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout-and-install
      # - test:
      #    requires:
      #       - checkout-and-install
      - build:
          requires:
            - checkout-and-install
            # - test
      # - deploy-dev:
      #     requires:
      #       - build
